# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g3sc5g0WDDDNeF_tD2BJPQV-FbC4pnWl
"""

pip install tavily-python

from tavily import TavilyClient
import json

tavily_client = TavilyClient(api_key = "Your API Key Here")

response = tavily_client.search(
    query = "who is Leo Messi?",
    search_depth = "advanced",
    topic = "news",
    time_range = "w", #last week
    num_results = 10,
    include_raw_content=False,
    include_links=False,
    include_images=False,
    exclude_domains=["spacy-site.com", "low-quality-domain.com"]
)
for res in response["results"]:
  print(res["title"], res["url"])
  print(res["content"][:50], "...")

